region               = "asia-east1"
vpc_name             = "vpc-alpha"
subnet_name          = "subnet-alpha"
primary_ip_cidr      = "10.0.0.0/16"
subnet_pods_name     = "pods"
pods_ip_cidr         = "10.10.0.0/16"
subnet_services_name = "services"
services_ip_cidr     = "10.20.0.0/20"
