name: CI Pipeline for Production

on:
  pull_request:
    branches:
      - main
    paths:
      - '2.nginx/**'
      - '3.manifest/kustomize/**.yaml'

jobs:
  CI-Production:
    uses: ./.github/workflows/base-ci.yaml
    with:
      KUSTOMIZE_OVERLAY: ./3.manifest/kustomize/overlay/production
      NAMESPACE: production
      WORKSPACE: production
    secrets: inherit
