name: CI/CD Pipeline for Alpha

on:
  workflow_dispatch:

jobs:
  CICD-Alpha:
    uses: ./.github/workflows/base-cicd.yaml
    with:
      KUSTOMIZE_OVERLAY: ./3.manifest/kustomize/overlay/alpha
      NAMESPACE: alpha
      WORKSPACE: alpha
    secrets: inherit
